#!/usr/bin/env bash
#Read the /etc/passwd file line by line

while IFS=: read -r username password uid gid comment homedir shell; do
    echo "The user $username is part of the group $gid gang, lives in $homedir, and rides $shell."
    echo "USER ID's place is protected by the passcode $password."
    echo "More info about the user here: $comment"
    echo  # Add an empty line for readability
done < /etc/passwd
