#!/usr/bin/env bash
#Displays Best School 10 times using while loop.
#on the 9th iteration, displays "Hi" before "Best School".

count=0
while [ $count -le 10 ]; do
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    
    else
    fi
        echo "Best School"
    count=$((count + 1))
done
