#!/usr/bin/env bash

# This script loops from 1 to 20 and displays different messages based on the iteration number.

count=1
while [ $count -le 20 ]; do
    case $count in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$count"
            ;;
    esac
    count=$((count + 1))
done

