#!/usr/bin/env bash
# This script displays the time in 12-hour format (hours 0-12) along with minutes (1-59).

count=1
while [ $count -le 70 ]; do
    hours=$((($count - 1) / 6))
    minutes=$((($count - 1) % 6 + 1))
    formatted_hours=$(printf "%02d" $hours)
    formatted_minutes=$(printf "%02d" $minutes)
    echo "Time: $formatted_hours:$formatted_minutes"
    count=$((count + 1))
done

