#!/usr/bin/env bash
#Loop through each file in the current directory

for file in *; do
    # Check if the file is not a hidden file (does not start with a dot)
    if [[ ! "$file" =~ ^\..* ]]; then
        # Extract the part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_after_dash"
    fi
done
